# Generated by Django 5.2.17 on 2026-09-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='planning', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('planned_start_date__isnull', True), ('planned_end_date__isnull', True), ('planned_end_date__gte', models.F('planned_start_date')), _connector='OR'), name='projects_project_planned_dates_order', violation_error_message='A data final não pode ser anterior à inicial.')],
            },
        ),
    ]
