# Generated by Django 5.2.17 on 2026-09-10 00:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField()),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_entries', to='projects.projectstage')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('progress_percentage__gte', Decimal('0.00')), ('progress_percentage__lte', Decimal('100.00'))), name='progress_percentage_range', violation_error_message='O percentual deve estar entre 0 e 100.'), models.UniqueConstraint(fields=('stage', 'progress_date'), name='progress_stage_date_unique')],
            },
        ),
    ]
