# Generated by Django 5.2.17 on 2026-09-06 18:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.projectstage')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='budgets_budgetitem_quantity_positive', violation_error_message='A quantidade deve ser maior que zero.'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='budgets_budgetitem_unit_price_nonnegative', violation_error_message='O preço unitário não pode ser negativo.')],
            },
        ),
    ]
