# Generated by Django 5.2.17 on 2026-09-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='projects.projectstage')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('planned_end_date__gte', models.F('planned_start_date'))), name='planning_stageplan_planned_dates_order', violation_error_message='A data final não pode ser anterior à inicial.')],
            },
        ),
    ]
